const DIFFICULTY = 3;
const MINE_RATE = 3000;// DYNAMIC DIFFICULTY
const INITIAL_BALANCE = 500;
//reward transaction
const MINING_REWARD = 50;
const SHARDNUM = 2;//

module.exports={DIFFICULTY,MINE_RATE, INITIAL_BALANCE, MINING_REWARD, SHARDNUM};
//module.exports={DIFFICULTY, INITIAL_BALANCE, MINING_REWARD, SHARDNUM};